#    
name: Build Result

on:
  push:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'

jobs:
  login-and-build:
    name: Login, Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: art181
          password: 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
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: result
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/example-voting-app-result:latest
            ghcr.io/${{ github.repository_owner }}/example-voting-app-result:${{ github.sha }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      
