#
name: Build Result

on:
  push:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: art181
          password: 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
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: result
          push: false
          load: true
          tags: ghcr.io/${{ github.repository }}/example-voting-app-result:latest
          platforms: linux/amd64

      - name: Test image
        run: |
          docker image ls
          docker run --rm ghcr.io/${{ github.repository }}/example-voting-app-result:latest echo "Image test successful"
