name: Build Result
# Template source: https://github.com/dockersamples/.github/blob/main/templates/call-docker-build.yaml

on:
  push:
    branches:
      - main
    paths:
      - result/**
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - main
    paths:
      - result/**
      - '.github/workflows/call-docker-build-result.yaml'

jobs:
  call-docker-build:
    name: Result Call Docker Build
    uses: dockersamples/.github/.github/workflows/reusable-docker-build.yaml@main
    permissions:   
      contents: read
      packages: write
      pull-requests: write
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/dockersamples/example-voting-app-result
      tag-rules: |
        type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=raw,value=before,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=raw,value=after,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
        type=ref,event=pr
      context: result
      platforms: linux/amd64,linux/arm64,linux/arm/v7
      comment-enable: true

  ghcr-login:
    name: Login to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: art181
          password: ${{ MY_SECRET_NAME }}
