name: Build Result

on:
  push:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'result/**'
      - '.github/workflows/call-docker-build-result.yaml'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # You need 'write' permission here to push
    
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: art181  # Use repository owner for safety
          password: ${{ MY_SECRET_NAME }}  # Reference the secret
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: result  # Only build contents of the 'result' folder
          push: true  # Push the image to GHCR
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/example-voting-app-result:latest
          platforms: linux/amd64
          
      - name: Test image
        run: |
          docker image ls
          docker run --rm ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/example-voting-app-result:latest echo "Image test successful"
